[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn flask_api_server:app --bind 0.0.0.0:$PORT --timeout 120"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
